# -*- coding: utf-8 -*-
"""resume_parser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C31qmrt-v8MRxbRmtOO7IK65pUpPDMz8
"""

!pip install spacy pdfplumber nltk
!python -m spacy download en_core_web_sm

import spacy
import pdfplumber
import re
import json

nlp = spacy.load("en_core_web_sm")
print("SpaCy model loaded")

from google.colab import files

uploaded = files.upload()
resume_path = list(uploaded.keys())[0]
print("Uploaded file:", resume_path)

def extract_text_from_pdf(pdf_path):
    text = ""
    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"
    return text

def extract_name(text):
    lines = [line.strip() for line in text.split("\n") if line.strip()]

    email_pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'

    for i, line in enumerate(lines):
        if re.search(email_pattern, line):
            # Look above email for name
            for j in range(i - 1, max(i - 5, -1), -1):
                candidate = lines[j]
                words = candidate.split()

                if (
                    2 <= len(words) <= 3 and
                    all(w[0].isupper() for w in words) and
                    not any(w.lower() in SKILLS_DB for w in words)
                ):
                    return candidate
    return None

def extract_email(text):
    pattern = r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'
    match = re.search(pattern, text)
    return match.group() if match else None

def extract_phone(text):
    pattern = r'(\+91[\s-]?)?[6-9]\d{9}'
    match = re.search(pattern, text)
    return match.group() if match else None

SKILLS_DB = [
    "python", "java", "c++", "machine learning", "deep learning",
    "nlp", "sql", "django", "flask", "tensorflow", "pytorch"
]

def extract_skills(text):
    text = text.lower()
    return list({skill for skill in SKILLS_DB if skill in text})

EDU_KEYWORDS = [
    "bachelor", "master", "b.tech", "m.tech",
    "b.e", "m.e", "degree", "phd"
]

def extract_education(text):
    education = []
    for line in text.split("\n"):
        for word in EDU_KEYWORDS:
            if word in line.lower():
                education.append(line.strip())
    return list(set(education))

def extract_experience(text):
    pattern = r'(\d+)\+?\s+years?'
    matches = re.findall(pattern, text.lower())
    if matches:
        return [f"{max(matches)} years experience"]
    return []

def parse_resume(file_path):
    text = extract_text_from_pdf(file_path)

    data = {
        "name": extract_name(text),
        "email": extract_email(text),
        "phone": extract_phone(text),
        "skills": extract_skills(text),
        "education": extract_education(text),
        "experience": extract_experience(text)
    }

    return data

parsed_data = parse_resume(resume_path)
print(json.dumps(parsed_data, indent=4))